import type { NextPage } from 'next';
import Head from 'next/head';
import PageCover from '../components/PageCover';
import Container from '../components/Container';

const Home: NextPage = () => {
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <PageCover />
      <Container>
        App
      </Container>
    </div>
  )
}

export default Home
